name: Deploy to Public Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to public repository
        env:
          TARGET_REPO: zlownet/Sungard-Minecraft-Server
        run: |
          git remote add public https://x-access-token:${{ secrets.TOKEN }}@github.com/$TARGET_REPO.git
          git push public main --force
